### ISSUE TITLE
libsqlite3 requirement

### ISSUE THREAD

**Issue by sergiomeneses** [hasezoey/yt-downloader-rust#16]
When compiling i get this error:

```bash
note: /usr/bin/ld: cannot find -lsqlite3: No such file or directory
```

I need to install `libsqlite3-dev` to work, i think this is because of [this](https://github.com/diesel-rs/diesel/issues/673)

May we should update the requirements section on README.

**Comment by hasezoey** [comment]
are you sure `libsqlite3-dev` is required and not just `libsqlite3` / `sqlite3`?

**Comment by hasezoey** [comment]
i have updated the requirements section to have both build and "just run" requirements, with actual testing via docker container of `ubuntu` and `archlinux` and should cover most cases
