### ISSUE TITLE
Usage of libytdlr

### ISSUE THREAD

**Issue by aaalloc** [hasezoey/yt-downloader-rust#18]
Hi !

I saw that on crates folders you have a libytdlr folder, I was wondering if it can be used as an API for yt-dlp ? If yes, are they any documentation about it ? I would be really interested using your crate because I'm in a situation where basically I need to do some call to yt-dlp  and I don't find any good API in Rust for doing that properly.

**Comment by hasezoey** [comment]
i dont know if libytdlr is what you want, it is not a general-purpose interface for yt-dlp, it is build with some specific functionality in mind (download, rethumbnail), maybe have a look at crate [`youtube_dl`](https://crates.io/crates/youtube_dl) if that is what you search for.

though i will not prevent you from using libytdlr and may also accommodate some feature requests, but the current state is that it is purpose build for the binary.

also note that most options for the download [are currently hard-coded](https://github.com/hasezoey/yt-downloader-rust/blob/0f3c7135f662d70d48da02c5ef28cd1679a50a93/crates/libytdlr/src/main/download.rs#L152-L284) (like adding thumbnails, quality select is always best and output format is either mp3 (audio only) or mkv (video))

PS: also note that i do not plan to have this package (and binary) on crates.io

**Comment by aaalloc** [comment]
I've already tried [youtube_dl](https://crates.io/crates/youtube_dl) but it has some problem when using custom args, I will maybe try harder or searching another lib.

Thank you for your informations !

**Comment by hasezoey** [comment]
i will close this question as "answered", if there should be any specific questions about usage (aside from the mentioned limitations) or refactor requests, please open a new discussion or issue detailing those

**Comment by hasezoey** [comment]
As a slight update, both crates are now published to crates.io and `libytdlr` *can* be used outside of the `ytdlr` binary, though there are likely still places that could be improved.
